# Join message (PAPI is supported)
joinMessage: '{{player}} joined the game.'
joinMessageJson: '{"text": "{{player}} joined the game.", "color": "yellow"}'
# Quit message
quitMessage: '{{player}} left the game.'
quitMessageJson: '{"text": "{{player}} left the game.", "color": "yellow"}'
# use json version or normal version.
useJsonVersion: true
# Monitor config file change/delete and reload/release config file.
fileWatchService: true