# Join message
joinMessage: '{{player}} joined the server.'
joinMessageJson: '{"text": "{{player}} joined the server.", "color": "yellow"}'
# use json version or normal version.
useJsonVersion: true
# Monitor config file change/delete and reload/release config file.
fileWatchService: true